### ISSUE TITLE
Error on npm start

### ISSUE THREAD

**Issue by gilmaik** [davinkevin/angularjs-jspm-seed#18]
When running `npm start` : 

![err jspm](https://cloud.githubusercontent.com/assets/5844767/15217251/f2619fde-185a-11e6-9689-af103746162b.png)

My current configuration : 
gulp version : CLI version 3.9.1
npm version : 3.8.6

**Comment by davinkevin** [comment]
We reproduce the problem, it seems to be linked to the npm version and the non-deterministic way to handle dependencies (https://docs.npmjs.com/how-npm-works/npm3-dupe | https://docs.npmjs.com/how-npm-works/npm3-nondet)

The only solution we found (thanks @aubm) is to stay on v2 of npm.

**Comment by gilmaik** [comment]
Thanks for the quick answer. I'll try that.

**Comment by gilmaik** [comment]
It is now working. I had an error with http-server : 

`TypeError: The header content contains invalid characters`

I got rid of this by updating the http-server from 0.8.5 to 0.9.0.
