### ISSUE TITLE
feat(compress): add gzip compression

### ISSUE THREAD

**Issue by davinkevin** [davinkevin/angularjs-jspm-seed#6]
Using https://www.npmjs.com/package/gulp-gzip

``` js
import gzip from 'gulp-gzip';

gulp.task('build-js', () => {
  return gulp.src(`${paths.releaseDir}/${paths.app.name}.js`)
    .pipe(sourcemaps.init({loadMaps: true}))
    .pipe(ngAnnotate())
    .pipe(uglify({ compress : false }))
    .pipe(rename({suffix : '.min'}))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest(paths.releaseDir))
    .pipe(gzip())
    .pipe(gulp.dest(paths.releaseDir))
});
```

And modify index.html to load gz instead of js

**Comment by davinkevin** [comment]
We should use for "serve-prod" a system like https://www.npmjs.com/package/connect-gzip-static to serve gz if present and compatible and js / css in other case. This require browser-sync to serve file in prod mode.

After inspection, CSS gzip is divided by 6 and JS by 3

**Comment by aubm** [comment]
Closing that one as serve-prod should not be used in actual production anyway.
